version: '3.8'

services:
  rchan4:
    image: pasta04/rchan4
    container_name: rchan4
    volumes:
      - ./config:/usr/src/app/config
    restart: always
    # 外向けのポート:中のポート
    ports:
      - 3000:80
